/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        base:             '#0C0C0C',
        surface:          '#141414',
        'surface-raised': '#1C1C1C',
        'surface-inset':  '#0A0A0A',
        border:           '#2A2A2A',
        accent:           '#E8A030',
        'accent-hover':   '#D4911F',
        'accent-dim':     '#3D2E0F',
        'accent-text':    '#F5C76E',
        'text-primary':   '#F4F4F5',
        'text-secondary': '#A1A1AA',
        'text-disabled':  '#666672',
        success:          '#16A34A',
        warning:          '#B45309',
        danger:           '#B91C1C',
      },
      fontFamily: {
        display: ['"Instrument Serif"', 'serif'],
        sans:    ['"DM Sans"', 'system-ui', 'sans-serif'],
        mono:    ['"DM Mono"', 'monospace'],
      },
      fontSize: {
        display: ['clamp(36px, 5vw, 56px)', { lineHeight: '1.1' }],
        h1:      ['28px', { lineHeight: '1.2', fontWeight: '500' }],
        h2:      ['20px', { lineHeight: '1.3', fontWeight: '500' }],
        h3:      ['16px', { lineHeight: '1.4', fontWeight: '500' }],
        body:    ['15px', { lineHeight: '1.6' }],
        sm:      ['13px', { lineHeight: '1.5' }],
        caption: ['11px', { lineHeight: '1.4', letterSpacing: '0.06em' }],
      },
      borderRadius: {
        DEFAULT: '8px',
        none:    '0',
        sm:      '4px',
        md:      '5px',
        lg:      '8px',
        xl:      '12px',
        '2xl':   '16px',
        full:    '9999px',
      },
      boxShadow: {
        card:      '0 1px 3px rgba(0,0,0,0.4), 0 1px 2px rgba(0,0,0,0.3)',
        modal:     '0 8px 32px rgba(0,0,0,0.6)',
        glow:      '0 0 40px rgba(232,160,48,0.15)',
        'glow-lg': '0 0 80px rgba(232,160,48,0.2)',
      },
      keyframes: {
        fadeInUp:   { from: { opacity: '0', transform: 'translateY(20px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        float:      { '0%,100%': { transform: 'translateY(0px)' }, '50%': { transform: 'translateY(-12px)' } },
        pulse_glow: { '0%,100%': { opacity: '0.6', transform: 'scale(1)' }, '50%': { opacity: '1', transform: 'scale(1.05)' } },
      },
      animation: {
        'fade-in-up': 'fadeInUp 0.55s ease forwards',
        'float':      'float 4s ease-in-out infinite',
        'pulse-glow': 'pulse_glow 3s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
